language: cpp
os:
  - linux
compiler:
  - gcc
script:
  - docker run -t ubuntu:14.04 uptime
dist: trusty
sudo: false
install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install gettext gtk+ gconf'

addons:
  apt:
    packages:
    - cmake
    - libgtk2.0-dev
    - libgconf2-dev
    - libgstreamer1.0-dev
