language: cpp
cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"
os:
- linux
- osx
compiler:
- gcc
- clang
install:
- '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install meson gettext gtk+3 jsoncpp'
script:
- '[ "$TRAVIS_OS_NAME" != osx ] || { export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" && meson builddir && ninja -v -C builddir test; }'
- env
- '[ "$TRAVIS_OS_NAME" != linux ] || make -f scripts/Makefile travis'
dist: xenial
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
env:
  global:
    secure: eyR9+pbzRtjG35BrWjHfSngD2N0VXJLCweyLkaiInuQCc1iTmsCetXP/wHGHcn5u02k3yBw31dlh4/r7cvXlpZrEJDV60U/wzVaezO44pUNZCiEngdhnBQS2iiFeAsHFbHrXMHVS6x+80wJfntRVZ069/xvuvcC/CWgKhVmhfn8=
