name: iptux # you probably want to 'snapcraft register <name>'
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Intranet communication tool for Linux # 79 char long summary
license: GPL-2.0+
description: |
  iptux is an “IP Messenger” client for Linux.
  .
  It can:
    - auto-detect other clients on the intranet.
    - send message to other clients.
    - send file to other clients.
  .
  It is (supposedly) compatible with 飞鸽传书 (Feige) and 飞秋 (FeiQ)
  from China, and with the original “IP Messenger” clients from Japan
  as listed on http://ipmsg.org/ including g2ipmsg and xipmsg in Debian.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

slots:
  dbus-iptux:
    interface: dbus
    bus: session
    name: io.github.iptux-src.iptux

apps:
  iptux:
    command: usr/bin/iptux
    desktop: usr/share/applications/io.github.iptux-src.iptux.desktop
    extensions: [gnome-3-28]
    slots:
      - dbus-iptux
    plugs: [home, network, gsettings, unity7]

parts:
  iptux:
    source-type: git
    source: https://github.com/iptux-src/iptux.git
    build-packages: [gettext, libgoogle-glog-dev, libjsoncpp-dev, libsigc++-2.0-dev, xvfb, libxml2-utils]
    plugin: meson
    meson-parameters: ["--prefix=/snap/iptux/current/usr"]
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|Icon=iptux-icon|Icon=/usr/share/iptux/pixmaps/icon/iptux-icon.png|g' share/applications/io.github.iptux-src.iptux.desktop.in
    override-build: |
      snapcraftctl build
      xvfb-run -a meson test -C snapbuild --verbose --no-stdsplit
    organize:
      snap/iptux/current/usr: usr
    stage-packages:
      - libgflags2.2
      - libgoogle-glog0v5
      - libjsoncpp1
      - libsigc++-2.0-0v5
      - try:
        - libunwind8 # not available in s390x

