name: iptux # you probably want to 'snapcraft register <name>'
version: "git" # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: iptux
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core22

slots:
  dbus-iptux:
    interface: dbus
    bus: session
    name: io.github.iptux_src.iptux

apps:
  iptux:
    command: usr/bin/iptux
    desktop: usr/share/applications/io.github.iptux_src.iptux.desktop
    extensions: [gnome]
    slots:
      - dbus-iptux
    plugs: [home, network, gsettings, unity7]

parts:
  iptux:
    source-type: git
    source: https://github.com/iptux-src/iptux.git
    build-packages:
      [
        gettext,
        libgoogle-glog-dev,
        libjsoncpp-dev,
        libsigc++-2.0-dev,
        libayatana-appindicator3-dev,
        xvfb,
        libxml2-utils,
        appstream,
      ]
    plugin: meson
    meson-parameters: ["--prefix=/snap/iptux/current/usr"]
    override-pull: |
      snapcraftctl pull
    override-build: |
      snapcraftctl build
      sed -i -e 's|Icon=iptux-icon|Icon=/usr/share/iptux/pixmaps/icon/iptux-icon.png|g' \
        $SNAPCRAFT_PART_INSTALL/snap/iptux/current/usr/share/applications/io.github.iptux_src.iptux.desktop
      # xvfb-run -a meson test -C snapbuild --verbose --no-stdsplit
    organize:
      snap/iptux/current/usr: usr
    stage-packages:
      - libgflags2.2
      - libgoogle-glog0v5
      - libjsoncpp25
      - libsigc++-2.0-0v5
      - libayatana-appindicator3-1
      - libunwind8
    parse-info: [usr/share/metainfo/io.github.iptux_src.iptux.metainfo.xml]
